name: My Manual Windows Workflow with Parameters

on: 
  workflow_dispatch:
          inputs:
            param1:
              description: 'param1'
            param2:
              description: 'param2'
jobs:
  my-job:
    runs-on: windows-latest

    steps:
      - name: Hello
        shell: pwsh
        run: |
          Write-Host "Parameter 1: ${{ github.event.inputs.param1 }}"
          Write-Host "Parameter 2: ${{ github.event.inputs.param2 }}"
