name: My Manual Windows Workflow with Parameters

on: 
  workflow_dispatch:
          inputs:
            param1:
              description: 'param1'
            param2:
              description: 'param2'
jobs:
  my-job:
    runs-on: windows-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4.1.1
        
      - name: Load environment from YAML
        uses: doughepi/yaml-env-action@v1.0.0
        with:
            files: ./variables/vars.yml # Pass a space-separated list of configuration files. Rightmost files take precedence.
    
      - name: Hello
        shell: pwsh
        run: |
          Write-Host "Parameter 1: ${{ github.event.inputs.param1 }}"
          Write-Host "Parameter 2: ${{ github.event.inputs.param2 }}"
